"""init schema

Revision ID: 21439761fa41
Revises: 
Create Date: 2026-04-28 07:03:28.689285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21439761fa41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.create_index('idx_audit_time', ['timestamp'], unique=False)

    op.create_table('todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('created', sa.Text(), nullable=False),
    sa.Column('done_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['todos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index('idx_todos_active', ['deleted_at'], unique=False)
        batch_op.create_index('idx_todos_parent', ['parent'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index('idx_todos_parent')
        batch_op.drop_index('idx_todos_active')

    op.drop_table('todos')
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_time')

    op.drop_table('audit')
    # ### end Alembic commands ###
